ALTER TABLE `consent_instances` DROP FOREIGN KEY `consent_instances_attachment_id_clinical_attachments_id_fk`;
--> statement-breakpoint
ALTER TABLE `document_deliveries` DROP FOREIGN KEY `document_deliveries_attachment_id_clinical_attachments_id_fk`;
--> statement-breakpoint
ALTER TABLE `invoice_items` DROP FOREIGN KEY `invoice_items_product_id_products_id_fk`;
--> statement-breakpoint
ALTER TABLE `invoice_items` DROP FOREIGN KEY `invoice_items_service_id_services_id_fk`;
--> statement-breakpoint
ALTER TABLE `clinical_attachments` ADD CONSTRAINT `attachments_id_encounter_unique` UNIQUE(`id`,`clinical_encounter_id`);--> statement-breakpoint
ALTER TABLE `clinical_attachments` ADD CONSTRAINT `attachments_size_check` CHECK (`clinical_attachments`.`size_bytes` > 0);--> statement-breakpoint
ALTER TABLE `consent_instances` ADD CONSTRAINT `consent_acceptance_check` CHECK ((`consent_instances`.`status` = 'printed' AND `consent_instances`.`accepted_at` IS NULL AND `consent_instances`.`acceptance_method` IS NULL AND `consent_instances`.`attachment_id` IS NULL) OR (`consent_instances`.`status` = 'accepted' AND `consent_instances`.`accepted_at` IS NOT NULL AND `consent_instances`.`acceptance_method` IS NOT NULL AND `consent_instances`.`attachment_id` IS NOT NULL));--> statement-breakpoint
ALTER TABLE `consent_template_versions` ADD CONSTRAINT `consent_version_positive_check` CHECK (`consent_template_versions`.`version` > 0);--> statement-breakpoint
ALTER TABLE `document_deliveries` ADD CONSTRAINT `document_deliveries_identity_check` CHECK ((`document_deliveries`.`document_type` = 'attachment' AND `document_deliveries`.`attachment_id` IS NOT NULL AND `document_deliveries`.`consent_instance_id` IS NULL AND `document_deliveries`.`template_version_id` IS NULL) OR (`document_deliveries`.`document_type` = 'consent' AND `document_deliveries`.`attachment_id` IS NULL AND `document_deliveries`.`consent_instance_id` IS NOT NULL AND `document_deliveries`.`template_version_id` IS NULL) OR (`document_deliveries`.`document_type` = 'consent_draft' AND `document_deliveries`.`attachment_id` IS NULL AND `document_deliveries`.`consent_instance_id` IS NULL AND `document_deliveries`.`template_version_id` IS NOT NULL) OR (`document_deliveries`.`document_type` = 'invoice_report' AND `document_deliveries`.`attachment_id` IS NULL AND `document_deliveries`.`consent_instance_id` IS NULL AND `document_deliveries`.`template_version_id` IS NULL));--> statement-breakpoint
ALTER TABLE `document_deliveries` ADD CONSTRAINT `document_deliveries_result_check` CHECK ((`document_deliveries`.`status` = 'pending' AND `document_deliveries`.`completed_at` IS NULL AND `document_deliveries`.`http_status` IS NULL) OR (`document_deliveries`.`status` IN ('completed', 'failed') AND `document_deliveries`.`completed_at` IS NOT NULL AND `document_deliveries`.`http_status` BETWEEN 100 AND 599));--> statement-breakpoint
ALTER TABLE `invoice_items` ADD CONSTRAINT `invoice_items_resource_check` CHECK (`invoice_items`.`product_id` IS NULL OR `invoice_items`.`service_id` IS NULL);--> statement-breakpoint
ALTER TABLE `consent_instances` ADD CONSTRAINT `consent_attachment_encounter_fk` FOREIGN KEY (`attachment_id`,`clinical_encounter_id`) REFERENCES `clinical_attachments`(`id`,`clinical_encounter_id`) ON DELETE restrict ON UPDATE restrict;--> statement-breakpoint
ALTER TABLE `consent_instances` ADD CONSTRAINT `consent_instances_attachment_id_clinical_attachments_id_fk` FOREIGN KEY (`attachment_id`) REFERENCES `clinical_attachments`(`id`) ON DELETE restrict ON UPDATE restrict;--> statement-breakpoint
ALTER TABLE `document_deliveries` ADD CONSTRAINT `document_deliveries_attachment_id_clinical_attachments_id_fk` FOREIGN KEY (`attachment_id`) REFERENCES `clinical_attachments`(`id`) ON DELETE restrict ON UPDATE restrict;--> statement-breakpoint
ALTER TABLE `invoice_items` ADD CONSTRAINT `invoice_items_product_id_products_id_fk` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE restrict ON UPDATE restrict;--> statement-breakpoint
ALTER TABLE `invoice_items` ADD CONSTRAINT `invoice_items_service_id_services_id_fk` FOREIGN KEY (`service_id`) REFERENCES `services`(`id`) ON DELETE restrict ON UPDATE restrict;