export { default as patientsRoutes } from './patients.routes'
export { default as authRoutes } from './auth.routes'
export { default as dashboardRoutes } from './dashboard.routes'
export { default as visitsRoutes } from './visits.routes'
export { default as stockRoutes } from './stock.routes'